INSERT INTO CATEGORY("CATEGORYNAME") VALUES('Fashion');
INSERT INTO CATEGORY("CATEGORYNAME") VALUES('Electronics');
INSERT INTO CATEGORY("CATEGORYNAME") VALUES('Books');
INSERT INTO CATEGORY("CATEGORYNAME") VALUES('Groceries');
INSERT INTO CATEGORY("CATEGORYNAME") VALUES('Medicines');


INSERT INTO USERS("USERNAME", "PASSWORD") VALUES('jack', 'pass_word');
INSERT INTO USERS("USERNAME", "PASSWORD") VALUES('bob', 'pass_word');
INSERT INTO USERS("USERNAME", "PASSWORD") VALUES('apple', 'pass_word');
INSERT INTO USERS("USERNAME", "PASSWORD") VALUES('glaxo', 'pass_word');

INSERT INTO ROLE("ROLENAME") VALUES('CONSUMER');
INSERT INTO ROLE("ROLENAME") VALUES('SELLER');

INSERT INTO USERS_ROLE("USERID", "ROLEID") VALUES(1, 1);
INSERT INTO USERS_ROLE("USERID", "ROLEID") VALUES(2, 1);
INSERT INTO USERS_ROLE("USERID", "ROLEID") VALUES(3, 2);
INSERT INTO USERS_ROLE("USERID", "ROLEID") VALUES(4, 2);

INSERT INTO PRODUCT("PRICE", "PRODUCTNAME", "CATEGORYID", "SELLERID") VALUES(2910, 'Apple iPad 10.2 8th Gen WiFi iOS Tablet', 2, 3);
INSERT INTO PRODUCT("PRICE", "PRODUCTNAME", "CATEGORYID", "SELLERID") VALUES(10, 'Crocin pain relief tablet', 5, 4);
INSERT INTO PRODUCT("PRICE", "PRODUCTNAME", "CATEGORYID", "SELLERID") VALUES(50, 'iPhone', 2, 4);

INSERT INTO CART("TOTALAMOUNT", "USERID") VALUES(20, 1);
INSERT INTO CART("TOTALAMOUNT", "USERID") VALUES(0, 2);

INSERT INTO CARTPRODUCT("CARTID", "PRODUCTID", "QUANTITY") VALUES(1, 2, 2);
